# Application configuration
spring.application.name=awe-boot
application.name=${project.artifactId}
application.acronym=${project.artifactId}
application.base.path=${user.home}/${project.artifactId}
filemanager.base.path=${application.base.path}
application.log.base.path=${application.base.path}/logs/${project.version}

# Profile
spring.profiles.active=local
logging.level.org.springframework.web=INFO

# Properties
properties.log=classpath:log4j2-app.properties

# Server configuration
server.servlet.context-path=/
server.port=8080
server.compression.enabled=true
server.compression.min-response-size=256
server.compression.mime-types=application/json,application/xml,text/html,text/xml,text/plain,text/css,application/javascript

# SPRING RESOURCES HANDLING (ResourceProperties)
spring.web.resources.add-mappings=true
spring.web.resources.cache.period=31557600
spring.web.resources.chain.cache=true
spring.web.resources.chain.compressed=true
spring.web.resources.chain.strategy.content.enabled=true
# Enable database update by Flyway
spring.flyway.enabled=true
awe.database.migration.modules=AWE,SCHEDULER,NOTIFIER,AWE-BOOT
################################################
# Database configuration
################################################
## Database HSQL
spring.datasource.url=jdbc:hsqldb:file:awe-tests/awe-boot/target/db/awe-boot
spring.datasource.username=sa
spring.datasource.password=

################################################
# Cache
################################################
spring.cache.type=jcache
spring.cache.jcache.config=classpath:ehcache.xml
# Redis server host.
spring.redis.host=localhost
# Login password of the redis server.
spring.redis.password=
# Redis server port.
spring.redis.port=6379

################################################
# Swagger configuration
################################################
swagger.enabled=true

################################################
# Session configuration
################################################
spring.session.store-type=none

################################################
# Email
################################################
awe.mail.enabled=true
# Mail authorization
awe.mail.auth=false
# Mail host
awe.mail.host=almeml1.almis.local
# Mail port
awe.mail.port=25
# Mail user
awe.mail.user=
# Mail password
awe.mail.pass=
# Mail debug
awe.mail.debug=true
# Mail SSL
awe.mail.ssl=true
# Mail TLS
awe.mail.tls=true
# Mail localhost
awe.mail.localhost=localhost

################################################
# Actuator management
################################################
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.health.ldap.enabled=false
management.health.redis.enabled=false

################################################
# Metrics management
################################################
wavefront.application.name=console-awe-boot
management.metrics.export.wavefront.enabled=false
management.metrics.export.wavefront.step=60s
management.metrics.export.wavefront.source=awe-cloud-server
spring.sleuth.async.enabled=false
#---
spring.config.activate.on-profile=dev
spring.cache.type=simple
#---
spring.config.activate.on-profile=cloud
spring.cache.type=redis
spring.session.store-type=redis
management.metrics.export.wavefront.enabled=true
management.health.redis.enabled=true
# Redis server host.
spring.redis.host=redis-service
# Login password of the redis server.
spring.redis.password=
# Redis server port.
spring.redis.port=6379