apiVersion: v1
kind: ConfigMap
metadata:
  name: awe-boot
  namespace: staging
data:
  application.properties: |-
    info.app.name=Awe Boot Application
    info.app.description=This is an awe application example
    # Redis key prefix
    spring.cache.redis.key-prefix=awe-boot::
    spring.session.redis.namespace=awe-boot:session
    ## Database MYSQL
    spring.datasource.url=jdbc:mysql://${MYSQL_URL}?\
      &verifyServerCertificate=true&useSSL=true&requireSSL=true\
      &clientCertificateKeyStoreUrl=file:/mnt/secrets/mysql-client-keystore.p12&clientCertificateKeyStorePassword=${MYSQL_CLIENT_KEYSTORE_PASSWORD}\
      &trustCertificateKeyStoreUrl=file:/mnt/secrets/truststore.jks&trustCertificateKeyStorePassword=${TRUSTSTORE_PASSWORD}
    spring.datasource.username=${MYSQL_USERNAME}
    spring.datasource.password=${MYSQL_PASSWORD}