apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- digest: sha256:aaaaaaaaaaaa
  name: registry.gitlab.com/aweframework/awe/awe-boot
  newName: registry.gitlab.com/aweframework/awe/awe-boot:4.4.3-SNAPSHOT

commonAnnotations:
  version: 4.4.3-SNAPSHOT

resources:
- awe-boot-deployment.yaml
