-- ------------------------------------------------------
-- UPDATE HISope columns IN audit tables
-- ------------------------------------------------------
ALTER TABLE HISope ALTER COLUMN HISope SET DATA TYPE CHAR(100);
ALTER TABLE HISAweAppPar ALTER COLUMN HISope SET DATA TYPE CHAR(100);
ALTER TABLE HISAweThm ALTER COLUMN HISope SET DATA TYPE CHAR(100);
ALTER TABLE HISAwePro ALTER COLUMN HISope SET DATA TYPE CHAR(100);
ALTER TABLE HISAweDbs ALTER COLUMN HISope SET DATA TYPE CHAR(100);
ALTER TABLE HISAweSit ALTER COLUMN HISope SET DATA TYPE CHAR(100);
ALTER TABLE HISAweMod ALTER COLUMN HISope SET DATA TYPE CHAR(100);
ALTER TABLE HISAweSitModDbs ALTER COLUMN HISope SET DATA TYPE CHAR(100);
ALTER TABLE HISAweModOpe ALTER COLUMN HISope SET DATA TYPE CHAR(100);
ALTER TABLE HISAweModPro ALTER COLUMN HISope SET DATA TYPE CHAR(100);
ALTER TABLE HISAweEmlSrv ALTER COLUMN HISope SET DATA TYPE CHAR(100);
ALTER TABLE HISAweScrCnf ALTER COLUMN HISope SET DATA TYPE CHAR(100);
ALTER TABLE HISAweScrRes ALTER COLUMN HISope SET DATA TYPE CHAR(100);
ALTER TABLE HISAweQue ALTER COLUMN HISope SET DATA TYPE CHAR(100);
