##############################
# Pipeline definition
##############################

include:
  # Security Products features
  - template: DAST.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: License-Scanning.gitlab-ci.yml

image: maven:3.8-openjdk-17-slim

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml -Dsettings.security=.m2/settings-security.xml -P!devtools --batch-mode --show-version"
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.color=false -Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_REPO_PATH: ".m2/repository"
  SAST_PULL_ANALYZER_IMAGES: "0"
  SAST_RUN_ANALYZER_TIMEOUT: 30m
  SONAR_OPTS: "-Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.organization=$SONAR_ORGANIZATION -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN -Dsonar.qualitygate.wait=true"
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  SKIP_TESTS: "-DskipTests"
  IT_OPTS: "-Dskip.junit=true -Dskip.karma=true -Dskip.selenium=false -DgenerateIntegrationReport=true"
  UT_OPTS: "-Dskip.frontend=true -DgenerateUnitReport=true"
  DEPLOY_OPTS: "-f awe-framework/pom.xml -DskipTests -Darchetype.test.skip=true -Dskip.javadoc=false -Dbuild.environment=production"
  CI_PROJECT_URL_SSH: "origin git@gitlab.com:aweframework/awe.git"
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci
  KUBERNETES_PROJECT_ID: wired-armor-229610
  KUBERNETES_CLUSTER_NAME: awe-boot-cluster
  API_URL: "$CI_API_V4_URL/projects/$CI_PROJECT_ID"
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the sonar task.
  # Security config
  DAST_WEBSITE: "https://staging.aweframework.com"
  DAST_TARGET_AVAILABILITY_TIMEOUT: 180
  DAST_BROWSER_SCAN: "true"
  DS_EXCLUDED_ANALYZERS: "gemnasium, gemnasium-python"

cache:
  - key: ${CI_COMMIT_REF_SLUG}
    policy: pull
    paths:
      - .m2/repository/

stages:
  - build
  - test
  - integration test
  - analysis
  - site
  - package
  - deploy
  - dast
  - release

.git_credentials_template: &git_credentials
  before_script:
    ## Push git credentials
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - git config --global user.email awe@almis.com
    - git config --global user.name "AWE Robot"
    - git remote set-url $CI_PROJECT_URL_SSH

##############################
# Pipeline rules
##############################

.if-default: &if-default
  if: '$CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_REF_NAME == "develop" || $CI_MERGE_REQUEST_IID'
.if-master: &if-master
  if: '$CI_COMMIT_REF_NAME == "master"'
.if-develop: &if-develop
  if: '$CI_COMMIT_REF_NAME == "develop"'
.if-merge-request: &if-merge-request
  if: '$CI_MERGE_REQUEST_IID'
.if-tag: &if-tag
  if: '$CI_COMMIT_TAG'

##############################
# Build stage
##############################

.build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS install $SKIP_TESTS
    - version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
    - echo "PROJECT_VERSION=$version" >> build.env
  rules:
    - <<: *if-default

.build-website:
  image: registry.gitlab.com/aweframework/docker-tools/website-build:latest
  stage: build
  script:
    - yarn --cwd website install
  cache: { }
  artifacts:
    paths:
      - website/build
    expire_in: 1 day

Build project:
  extends: .build
  artifacts:
    reports:
      dotenv: build.env
    paths:
      - awe-tests/awe-boot/target/awe-boot.war
    expire_in: 1 day
  cache:
    - key: ${CI_COMMIT_REF_SLUG}
      policy: pull-push
      paths:
        - .m2/repository/

Build project:jdk 18:
  extends: .build
  image: maven:3.8-openjdk-18-slim

Build website:
  extends: .build-website
  script:
    - yarn --cwd website install
    - yarn --cwd website build
  rules:
    - <<: *if-merge-request

Build website with i18n:
  extends: .build-website
  script:
    - yarn --cwd website install
    # Do translations
    - yarn --cwd website crowdin:sync
    - yarn --cwd website build
  resource_group: crowdin
  rules:
    - <<: *if-develop
    - <<: *if-master

##############################
# testing stage
##############################

# Unit testing extension
.unit-testing:
  stage: test
  allow_failure: false
  needs:
    - job: Build project
      artifacts: false
  script:
    - mvn $MAVEN_CLI_OPTS verify $UT_OPTS -P$TEST_NAME -Djacoco.file.name=jacoco-${TEST_NAME}-ut.exec -Doracle.jdbc.J2EE13Compliant=true -Doracle.jdbc.timezoneAsRegion=false
  rules:
    - <<: *if-default
  artifacts:
    paths:
      - "**/target/*.exec"
      - "**/target/surefire-reports"
      - "**/target/zerocode*.csv"
    when: always
    expire_in: 1 day
    reports:
      junit:
        - "**/target/surefire-reports/TEST-*.xml"

All UT:
  extends: .unit-testing
  script:
    - mvn $MAVEN_CLI_OPTS verify $UT_OPTS -Djacoco.file.name=jacoco-all-ut.exec

Oracle Tests:
  extends: .unit-testing
  services:
    - epiclabs/docker-oracle-xe-11g
  variables:
    ORACLE_ALLOW_REMOTE: "true"
    ORACLE_PASSWORD: "$DATABASE_PASSWORD"
    RELAX_SECURITY: "1"
    TEST_NAME: oracle

MySQL Tests:
  extends: .unit-testing
  variables:
    MYSQL_DATABASE: "awetestdb"
    MYSQL_ROOT_PASSWORD: "$DATABASE_PASSWORD"
    TEST_NAME: mysql
  services:
    - mysql

SQL Server Tests:
  extends: .unit-testing
  image: registry.gitlab.com/aweframework/docker-tools/sqlserver-testing:latest
  variables:
    ACCEPT_EULA: Y
    SA_PASSWORD: "$DATABASE_PASSWORD"
    TEST_NAME: sqlserver
  before_script:
    - /opt/mssql-tools/bin/sqlcmd -S mssqlserver -U SA -P "$DATABASE_PASSWORD" -Q 'CREATE DATABASE awetestdb'
  services:
    - name: mcr.microsoft.com/mssql/server:2019-latest
      alias: mssqlserver

Frontend UT:
  stage: test
  image: registry.gitlab.com/aweframework/docker-tools/browsers-jdk11-node-maven:latest
  needs: [ ]
  cache: { }
  script:
    - mvn -f awe-framework/awe-client-angular/pom.xml $MAVEN_CLI_OPTS test
  artifacts:
    paths:
      - awe-framework/awe-client-angular/target/reports/karma/
    expire_in: 1 day
    reports:
      junit:
        - awe-framework/awe-client-angular/target/reports/junit/*.xml
  rules:
    - <<: *if-default

Javadoc test:
  stage: test
  needs:
    - job: Build project
      artifacts: false
  script:
    - mvn -f awe-framework/pom.xml $MAVEN_CLI_OPTS javadoc:aggregate-no-fork -Dskip.javadoc=false -Ptest-javadoc
  artifacts:
    paths:
      - awe-framework/target/site/apidocs
    expire_in: 1 day
  rules:
    - <<: *if-merge-request

##############################
# Integration testing stage
##############################

# Browser testing extension
.browser-testing:
  # Important! Do not use slim version (it doesn't have the necessary fonts)
  image: maven:3.8-openjdk-17
  stage: integration test
  allow_failure: true
  variables:
    SCREEN_WIDTH: 1440
    SCREEN_HEIGHT: 1080
    FF_NETWORK_PER_BUILD: "true"
  needs:
    - job: Build project
      artifacts: false
  script:
    - mvn -f awe-tests/awe-boot/pom.xml $MAVEN_CLI_OPTS verify $IT_OPTS -Dawe.test.browser=${BROWSER} -Dgroups="${TEST_TAGS}" -Djacoco.file.name=jacoco-${TEST_NAME}-it.exec -Djacoco.port=$TEST_PORT
    - echo "I am going to wait for 10 seconds only to ensure .exec file generation"
    - sleep 10
  artifacts:
    expose_as: 'Selenium reports'
    paths:
      - awe-tests/awe-boot/target/tests/
      - awe-tests/awe-boot/target/surefire-reports/
      - awe-tests/awe-boot/target/jacoco-${TEST_NAME}-it.exec
    expire_in: 1 day
    reports:
      junit:
        - awe-tests/awe-boot/target/surefire-reports/TEST-*.xml
    when: always
  rules:
    - <<: *if-default

.firefox-testing:
  extends: .browser-testing
  services:
    - name: selenoid/firefox
      alias: browser
    - name: registry.gitlab.com/aweframework/docker-tools/video-recorder:latest
      alias: recorder
  variables:
    BROWSER: service-firefox

.chrome-testing:
  extends: .browser-testing
  services:
    - name: selenoid/chrome
      alias: browser
    - name: registry.gitlab.com/aweframework/docker-tools/video-recorder:latest
      alias: recorder
  variables:
    BROWSER: service-chrome

Firefox IT Application and Integration:
  extends: .firefox-testing
  variables:
    TEST_NAME: firefox-application-integration
    TEST_TAGS: ApplicationIntegrationIT
    TEST_PORT: 6301

Firefox IT CRUD Criteria and Matrix:
  extends: .firefox-testing
  variables:
    TEST_NAME: firefox-crud-criteria-matrix
    TEST_TAGS: CRUDCriteriaMatrixIT
    TEST_PORT: 6302

Firefox IT Regression Websocket and Print:
  extends: .firefox-testing
  variables:
    TEST_NAME: firefox-regression-websocket-print
    TEST_TAGS: RegressionWebsocketPrintIT
    TEST_PORT: 6303

Firefox IT Scheduler:
  extends: .firefox-testing
  variables:
    TEST_NAME: firefox-scheduler
    TEST_TAGS: SchedulerIT
    TEST_PORT: 6304

Chrome IT Application and Integration:
  extends: .chrome-testing
  variables:
    TEST_NAME: chrome-application-integration
    TEST_TAGS: ApplicationIntegrationIT
    TEST_PORT: 6305

Chrome IT CRUD Criteria and Matrix:
  extends: .chrome-testing
  variables:
    TEST_NAME: chrome-crud-criteria-matrix
    TEST_TAGS: CRUDCriteriaMatrixIT
    TEST_PORT: 6306

Chrome IT Regression Websocket and Print:
  extends: .chrome-testing
  variables:
    TEST_NAME: chrome-regression-websocket-print
    TEST_TAGS: RegressionWebsocketPrintIT
    TEST_PORT: 6307

Chrome IT Scheduler:
  extends: .chrome-testing
  variables:
    TEST_NAME: chrome-scheduler
    TEST_TAGS: SchedulerIT
    TEST_PORT: 6308

##############################
# Analysis stage
##############################

Launch Sonar:
  image: registry.gitlab.com/aweframework/docker-tools/sonar:latest
  stage: analysis
  needs:
    - job: All UT
    - job: Oracle Tests
    - job: SQL Server Tests
    - job: MySQL Tests
    - job: Frontend UT
    - job: Firefox IT Application and Integration
    - job: Firefox IT CRUD Criteria and Matrix
    - job: Firefox IT Regression Websocket and Print
    - job: Firefox IT Scheduler
    - job: Chrome IT Application and Integration
    - job: Chrome IT CRUD Criteria and Matrix
    - job: Chrome IT Regression Websocket and Print
    - job: Chrome IT Scheduler
  cache:
    - key: ${CI_COMMIT_REF_SLUG}
      policy: pull
      paths:
        - .m2/repository/
    - key: ${CI_JOB_NAME}
      paths:
        - .sonar/cache
  script:
    - mvn $MAVEN_CLI_OPTS verify -Dskip.frontend=true -DgenerateCoverageReport=true sonar:sonar $SKIP_TESTS -Dskip.dependency-check=false -Darchetype.test.skip=true $SONAR_OPTS
    - cat awe-tests/awe-boot/target/coverage-reports/index.html | grep -o 'Total[^%]*%' | sed -e 's/Total/Jacoco-Test-Coverage:/g'
  artifacts:
    paths:
      - awe-tests/awe-boot/target/coverage-reports/
    expire_in: 1 week
  rules:
    - <<: *if-default

gemnasium-maven-dependency_scanning:
  stage: test
  rules:
    - <<: *if-default
  dependencies: ["Build project"]
  variables:
    MAVEN_CLI_OPTS: "-DskipTests --batch-mode"


license_scanning:
  stage: analysis
  needs: [ ]
  rules:
    - <<: *if-default

##############################
# Site stage
##############################

Generate javadoc & schemas:
  stage: site
  needs: [ ]
  script:
    - mvn $MAVEN_CLI_OPTS install site javadoc:aggregate $SKIP_TESTS -Darchetype.test.skip=true -Dskip.javadoc=false -Dskip.main=true -Dskip.frontend=true -Dbuild.environment=production -f awe-framework/pom.xml
  artifacts:
    paths:
      - awe-framework/target/site/apidocs
      - awe-framework/awe-generic-screens/src/main/resources/schemas/
    expire_in: 1 day
  rules:
    - <<: *if-master
    - <<: *if-develop

##############################
# Package stage
##############################

Build package:
  image: docker:latest
  stage: package
  cache: { }
  needs:
    - job: Build project
    - job: Launch Sonar
      artifacts: false
  services:
    - docker:dind
  script:
    # Gitlab container
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/aweframework/awe/awe-boot:$PROJECT_VERSION ./awe-tests/awe-boot
    - docker push registry.gitlab.com/aweframework/awe/awe-boot:$PROJECT_VERSION
    - digest=$(docker images registry.gitlab.com/aweframework/awe/awe-boot --format="{{.Digest}}" --digests)
    - echo "PACKAGE_DIGEST=$digest" >> build.env
    # Docker Hub container
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_TOKEN
    - docker build -t aweframework/awe-boot:$PROJECT_VERSION ./awe-tests/awe-boot
    - docker push aweframework/awe-boot:$PROJECT_VERSION
  artifacts:
    reports:
      dotenv: build.env
  rules:
    - <<: *if-develop
    - <<: *if-master

##############################
# Deploy stage
##############################

Deploy snapshot:
  stage: deploy
  needs:
    - job: Launch Sonar
  script:
    - mvn $MAVEN_CLI_OPTS deploy $DEPLOY_OPTS
  rules:
    - <<: *if-develop

Deploy Maven Central:
  stage: deploy
  image: registry.gitlab.com/aweframework/docker-tools/ci-release:latest
  before_script:
    ## Add gpg key to sign
    - gpg --batch --import <(echo "$GPG_PRIVATE_KEY")
  script:
    - mvn $MAVEN_CLI_OPTS deploy $DEPLOY_OPTS -DperformRelease=true
  rules:
    - <<: *if-tag

# Kubernetes deployment
.k8s_deploy:
  image: registry.gitlab.com/aweframework/docker-tools/ci-utilities:latest
  cache: { }
  variables:
    GIT_STRATEGY: none
  needs:
    - job: Build project
    - job: Launch Sonar
      artifacts: false
    - job: Build package
  stage: deploy
  script:
    - git clone ${GIT_REPO_AWE_CONFIG}
    - git config --global user.email ${GIT_REPO_CI_USER_EMAIL}
    - git config --global user.name "${GIT_REPO_CI_USER_NAME}"
    - cd awe-gke-config/${CI_ENVIRONMENT_SLUG}/awe-boot
    - kustomize edit set image registry.gitlab.com/aweframework/awe/awe-boot@${PACKAGE_DIGEST}
    - kustomize edit set annotation version:${PROJECT_VERSION}
    - kustomize build -o awe-boot-deployment.yaml
    - git commit . -m "Updated awe-boot kubernetes deployment ${CI_ENVIRONMENT_SLUG}"
    - git push origin master

Deploy staging:
  extends: .k8s_deploy
  environment:
    name: staging
    url: https://staging.aweframework.com
    kubernetes:
      namespace: staging
  rules:
    - <<: *if-develop

Deploy production:
  extends: .k8s_deploy
  environment:
    name: production
    url: https://demo.aweframework.com
    kubernetes:
      namespace: production
  rules:
    - <<: *if-master

dast:
  script:
    - export DAST_WEBSITE=${DAST_WEBSITE:-$(cat environment_url.txt)}
    - if [ -z "$DAST_WEBSITE$DAST_API_SPECIFICATION" ]; then echo "Either DAST_WEBSITE or DAST_API_SPECIFICATION must be set. See https://docs.gitlab.com/ee/user/application_security/dast/#configuration for more details." && exit 1; fi
    - /analyze
  needs:
    - job: Deploy staging
  rules:
    - <<: *if-develop

pages:
  image: docker:latest
  stage: deploy
  cache: { }
  needs:
    - job: Generate javadoc & schemas
    - job: Build website with i18n
  script:
    - mkdir -p .public/docs/schemas
    - cp -r awe-framework/target/site/apidocs .public/javadoc-api/
    - cp -r awe-framework/awe-generic-screens/src/main/resources/schemas/awe/*.xsd .public/docs/schemas/
    - cp -a website/build/. .public/
    - mv .public public
  artifacts:
    paths:
      - public
    expire_in: 1 day
  rules:
    - <<: *if-master
    - <<: *if-develop

##############################
# Release stage
##############################

Generate a new milestone:
  image: registry.gitlab.com/aweframework/docker-tools/ci-utilities:latest
  stage: release
  <<: *git_credentials
  script:
    ## Generate milestone
    - git checkout -f develop
    - git pull --rebase
    - chmod +x ./bin/milestone.sh
    - ./bin/milestone.sh $API_URL $API_TOKEN
  rules:
    - <<: *if-tag

Start a new release:
  image: registry.gitlab.com/aweframework/docker-tools/ci-release:latest
  cache: { }
  dependencies: [ ]
  stage: release
  <<: *git_credentials
  script:
    ## Generate changelog
    - git checkout $CI_COMMIT_REF_NAME
    - chmod +x ./bin/changelog.sh
    - ./bin/changelog.sh $API_URL $API_TOKEN "$CI_PROJECT_TITLE"
    - git checkout ./bin/changelog.sh
    - git add ./CHANGELOG.md
    - git commit -m "Generated CHANGELOG"
    ## Generate release
    - mvn -B gitflow:release -DskipTestProject=true -DpushRemote=true -DversionProperty=revision
  variables:
    GIT_STRATEGY: clone
  rules:
    - <<: *if-develop
      when: manual
      allow_failure: true

Notify new release:
  image: registry.gitlab.com/aweframework/docker-tools/ci-utilities:latest
  stage: release
  script:
    ## Generate milestone
    - chmod +x ./bin/sendmail.sh
    - ./bin/sendmail.sh $RELEASE_MAIL_TOKEN $RELEASE_MAIL_FROM $RELEASE_MAIL_TO $RELEASE_MAIL_TEMPLATE_ID
  rules:
    - <<: *if-tag
      when: delayed
      start_in: 1 hour
