version: "2"

services:

  tempo:
    image: grafana/tempo:2.10.8@sha256:f0561deb1c68ec44d6e6e7e4487f30106c4e5e768642077695b37958b105812a
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    restart: unless-stopped
    volumes:
      - ./tempo/tempo-config.yaml:/etc/tempo.yaml:ro
    ports:
      - "14268:14268" # jaeger ingest
      - "3200:3200"   # tempo
      - "4317:4317"   # otlp grpc
      - "4318:4318"   # otlp http
      - "9411:9411"   # zipkin
    depends_on:
      - loki

  prometheus:
    image: prom/prometheus:v2.55.1@sha256:2659f4c2ebb718e7695cb9b25ffa7d6be64db013daba13e05c875451cf51b0d3
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/config:/etc/prometheus/
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
      - --enable-feature=exemplar-storage
    ports:
      - "9090:9090"
    depends_on:
      - loki

  grafana:
    image: grafana/grafana-oss:9.5.21@sha256:681dc3261b0a8050809733e04d76f10300b91a1400cea17abe102b2cdef36b6d
    container_name: grafana
    restart: unless-stopped
    user: root
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/grafana-data:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    depends_on:
      - loki
      - prometheus

  loki:
    image: grafana/loki:2.9.17@sha256:c4a25af6f2709fa625d88ee5df494a332a85f30e9575854031667823ecc5be04
    container_name: loki
    restart: unless-stopped
    volumes:
      - ./loki/:/etc/loki/
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yaml

  promtail:
    image: grafana/promtail:2.9.17@sha256:b28495fdab552b183428c5b5cebbf258231fc5f00be7724be2bc091ad21ac390
    container_name: promtail
    restart: unless-stopped
    volumes:
      # Volume of promtail configuration
      - ./promtail:/etc/promtail/
      # Volume of promtail configuration
      - ../target/logs:/app/log/
    command: -config.file=/etc/promtail/promtail.yaml

  redis:
    image: redis:7.4.11@sha256:4fa24486b8bcca8eec45ee0eb166edc674795e53a2b53d1a9ef263eecebaac85
    container_name: redis-service
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  redisinsight:
    image: redislabs/redisinsight:latest@sha256:b5e19ee240abef6edb435871b90ff8a210995422e8e018ab61c0339d318a1f84
    ports:
      - "5540:5540"
