#!/usr/bin/env node
'use strict';

/**
 * Generates the XSD reference pages of the site (website/reference) from the AWE schemas.
 *
 * Usage: node scripts/xsd-reference/generate.js [--xsd-dir <dir>] [--out <dir>]
 *
 * The output folder is fully regenerated and git-ignored: the pages are never committed. To make sure a
 * wrong --out cannot delete anything else, the folder must be inside website/ and be either missing, empty
 * or marked as generated by this script.
 */

const fs = require('node:fs');
const path = require('node:path');

const {loadSchemas, buildReference} = require('./xsd-model');
const {renderPages} = require('./render');
const {coverageReport, formatReport} = require('./report');

const WEBSITE = path.resolve(__dirname, '..', '..');
const DEFAULT_XSD_DIR = path.resolve(WEBSITE, '..', 'awe-framework', 'awe-generic-screens', 'src', 'main', 'resources', 'schemas', 'awe');
const DEFAULT_OUT = path.join(WEBSITE, 'reference');
const MARKER = '.generated-by-xsd-reference';

function parseArgs(argv) {
	const options = {xsdDir: DEFAULT_XSD_DIR, out: DEFAULT_OUT};
	for (let i = 0; i < argv.length; i += 2) {
		const key = {'--xsd-dir': 'xsdDir', '--out': 'out'}[argv[i]];
		if (!key || argv[i + 1] === undefined) {
			throw new Error(`Usage: generate.js [--xsd-dir <dir>] [--out <dir>] (got "${argv.slice(i).join(' ')}")`);
		}
		options[key] = path.resolve(argv[i + 1]);
	}
	return options;
}

/** Throws unless the output folder can be emptied safely. */
function assertSafeOutput(out, root = WEBSITE) {
	const relative = path.relative(root, out);
	if (relative === '' || relative.startsWith('..') || path.isAbsolute(relative)) {
		throw new Error(`Refusing to use ${out} as output: it must be a folder inside ${root} (and not that folder itself)`);
	}
	if (fs.existsSync(out)) {
		if (!fs.statSync(out).isDirectory()) {
			throw new Error(`Refusing to use ${out} as output: it is not a directory`);
		}
		if (fs.readdirSync(out).length > 0 && !fs.existsSync(path.join(out, MARKER))) {
			throw new Error(`Refusing to delete ${out}: it is not generated by the XSD reference (no ${MARKER} file). Remove it or choose another --out`);
		}
	}
}

function assertSchemasFound(xsdDir) {
	if (!fs.existsSync(xsdDir) || !fs.statSync(xsdDir).isDirectory()) {
		throw new Error(
			`Cannot generate the XSD reference: the schema folder ${xsdDir} does not exist. ` +
			'The schemas live in awe-framework/awe-generic-screens of the repository, so build the website from a full checkout ' +
			'(not from website/ alone) or point to them with --xsd-dir <dir>.',
		);
	}
}

function generate({xsdDir = DEFAULT_XSD_DIR, out = DEFAULT_OUT, root = WEBSITE} = {}) {
	assertSafeOutput(out, root);
	assertSchemasFound(xsdDir);
	const reference = buildReference(loadSchemas(xsdDir));
	const pages = renderPages(reference);
	fs.rmSync(out, {recursive: true, force: true});
	fs.mkdirSync(out, {recursive: true});
	fs.writeFileSync(path.join(out, MARKER), 'Generated by website/scripts/xsd-reference. Do not edit: it is regenerated at every build.\n');
	for (const [file, content] of Object.entries(pages)) {
		fs.writeFileSync(path.join(out, file), content);
	}
	return {pages: Object.keys(pages), report: coverageReport(reference)};
}

/** Generates the reference only when it is missing: used by docusaurus.config.js so any docusaurus command finds it. */
function ensureGenerated(options = {}) {
	const out = options.out || DEFAULT_OUT;
	if (!fs.existsSync(path.join(out, 'index.mdx'))) {
		generate({...options, out});
	}
}

if (require.main === module) {
	const options = parseArgs(process.argv.slice(2));
	const {pages, report} = generate(options);
	console.log(`XSD reference: ${pages.length} pages written to ${path.relative(process.cwd(), options.out) || '.'}`);
	console.log(formatReport(report));
}

module.exports = {generate, ensureGenerated, parseArgs, assertSafeOutput};
