# Module Config File
# Configure application modules

# Utilities list
modules.list=app,notifier,scheduler,developer,tools,awe
module.awe=awe
module.tools=awe-tools
module.developer=awe-developer
module.scheduler=awe-scheduler
module.notifier=awe-notifier

# awe-angular-redux Paths
module.app=awe-react
module.app.documents=/static/docs/awe/