package com.almis.awe.developer.autoconfigure;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Guards the generated Spring configuration metadata, which feeds the properties reference.
 * Every property must carry a description, written as Javadoc on its field in the properties class
 * (or in additional-spring-configuration-metadata.json when no field exists to document).
 */
class ConfigurationMetadataTest {

  private static final Path METADATA = Path.of("target", "classes", "META-INF", "spring-configuration-metadata.json");

  @Test
  @DisplayName("Every configuration property has a description")
  void everyPropertyHasADescription() throws IOException {
    assertThat(METADATA).as("Metadata generated by spring-boot-configuration-processor").exists();
    JsonNode properties = new ObjectMapper().readTree(Files.readString(METADATA)).path("properties");
    assertThat(properties.isArray() && !properties.isEmpty())
      .as("The metadata lists the module's properties (an empty or missing list means the processor did not run)")
      .isTrue();

    List<String> undocumented = new ArrayList<>();
    properties.forEach(property -> {
      if (property.path("description").asText().isBlank()) {
        undocumented.add(property.path("name").asText());
      }
    });

    assertThat(undocumented).as("Properties without description").isEmpty();
  }
}
