apiVersion: v1
kind: ServiceAccount
metadata:
  name: awe-boot-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awe-boot-configmap-reader
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: awe-boot-configmap-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: awe-boot-configmap-reader
subjects:
  - kind: ServiceAccount
    name: awe-boot-sa
    namespace: default