apiVersion: v1
kind: ConfigMap
metadata:
  name: awe-react
data:
  application.properties: |-
    info.app.name=Awe React Application
    info.app.description=This is an awe application example with react engine
    spring.session.redis.namespace=awe-react:session
    spring.cache.redis.key-prefix=awe-react::
