apiVersion: v1
kind: ConfigMap
metadata:
  name: awe-react
data:
  application.properties: |-
    server.servlet.context-path=/react
    info.app.name=Awe React Application
    info.app.description=This is an awe application example with react engine
