--------------------------------------------------------
--  UPDATE HISope columns IN audit tables
--------------------------------------------------------
DROP INDEX IF EXISTS HISopeI1 on HISope;
DROP INDEX IF EXISTS HISAweAppParI1 on HISAweAppPar;
DROP INDEX IF EXISTS HISAweThmI1 on HISAweThm;
DROP INDEX IF EXISTS HISAweProI1 on HISAwePro;
DROP INDEX IF EXISTS HISAweDbsI1 on HISAweDbs;
DROP INDEX IF EXISTS HISAweSitI1 on HISAweSit;
DROP INDEX IF EXISTS HISAweModI1 on HISAweMod;
DROP INDEX IF EXISTS HISAweSitModDbsI1 on HISAweSitModDbs;
DROP INDEX IF EXISTS HISAweModOpeI1 on HISAweModOpe;
DROP INDEX IF EXISTS HISAweModProI1 on HISAweModPro;
DROP INDEX IF EXISTS HISAweEmlSrvI1 on HISAweEmlSrv;
DROP INDEX IF EXISTS HISAweScrCnfI1 on HISAweScrCnf;
DROP INDEX IF EXISTS HISAweScrResI1 on HISAweScrRes;
DROP INDEX IF EXISTS HISAweQueI1 on HISAweQue;

ALTER TABLE HISope ALTER COLUMN HISope CHAR(100) NULL;
ALTER TABLE HISAweAppPar ALTER COLUMN HISope CHAR(100) NULL;
ALTER TABLE HISAweThm ALTER COLUMN HISope CHAR(100) NULL;
ALTER TABLE HISAwePro ALTER COLUMN HISope CHAR(100) NULL;
ALTER TABLE HISAweDbs ALTER COLUMN HISope CHAR(100) NULL;
ALTER TABLE HISAweSit ALTER COLUMN HISope CHAR(100) NULL;
ALTER TABLE HISAweMod ALTER COLUMN HISope CHAR(100) NULL;
ALTER TABLE HISAweSitModDbs ALTER COLUMN HISope CHAR(100) NULL;
ALTER TABLE HISAweModOpe ALTER COLUMN HISope CHAR(100) NULL;
ALTER TABLE HISAweModPro ALTER COLUMN HISope CHAR(100) NULL;
ALTER TABLE HISAweEmlSrv ALTER COLUMN HISope CHAR(100) NULL;
ALTER TABLE HISAweScrCnf ALTER COLUMN HISope CHAR(100) NULL;
ALTER TABLE HISAweScrRes ALTER COLUMN HISope CHAR(100) NULL;
ALTER TABLE HISAweQue ALTER COLUMN HISope CHAR(100) NULL;

CREATE UNIQUE INDEX HISopeI1 ON HISope (HISope, HISdat, HISact);
CREATE UNIQUE INDEX HISAweAppParI1 ON HISAweAppPar (HISope, HISdat, HISact);
CREATE UNIQUE INDEX HISAweThmI1 ON HISAweThm (HISope, HISdat, HISact);
CREATE UNIQUE INDEX HISAweProI1 ON HISAwePro (HISope, HISdat, HISact);
CREATE UNIQUE INDEX HISAweDbsI1 ON HISAweDbs (HISope, HISdat, HISact);
CREATE UNIQUE INDEX HISAweSitI1 ON HISAweSit (HISope, HISdat, HISact);
CREATE UNIQUE INDEX HISAweModI1 ON HISAweMod (HISope, HISdat, HISact);
CREATE UNIQUE INDEX HISAweSitModDbsI1 ON HISAweSitModDbs (HISope, HISdat, HISact);
CREATE UNIQUE INDEX HISAweModOpeI1 ON HISAweModOpe (HISope, HISdat, HISact);
CREATE UNIQUE INDEX HISAweModProI1 ON HISAweModPro (HISope, HISdat, HISact);
CREATE UNIQUE INDEX HISAweEmlSrvI1 ON HISAweEmlSrv (HISope, HISdat, HISact);
CREATE UNIQUE INDEX HISAweScrCnfI1 ON HISAweScrCnf (HISope, HISdat, HISact);
CREATE UNIQUE INDEX HISAweScrResI1 ON HISAweScrRes (HISope, HISdat, HISact);
CREATE UNIQUE INDEX HISAweQueI1 ON HISAweQue (HISope, HISdat, HISact);