# Application configuration
application.name=test-react
application.acronym=test-react
application.base.path=/Users/pablojaviergarciamora/test-react
filemanager.base.path=${application.base.path}
application.log.base.path=${application.base.path}/logs/1.0.0-SNAPSHOT
application.theme=saga-purple
application.default.component.size=md

# Profile
spring.profiles.active=development
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=DEBUG
management.health.ldap.enabled=false

# Properties
properties.log=classpath:log4j2-app.properties

# Server configuration
server.servlet.context-path=/
server.port=8080
server.compression.enabled=true
server.compression.min-response-size=256
server.compression.mime-types=application/json,application/xml,text/html,text/xml,text/plain,text/css,application/javascript

# SPRING RESOURCES HANDLING (ResourceProperties)
spring.web.resources.add-mappings=true
spring.web.resources.cache.period=31557600
spring.web.resources.chain.cache=true
spring.web.resources.chain.compressed=true
spring.web.resources.chain.strategy.content.enabled=true

# Enable database update by Flyway
spring.flyway.enabled=true
awe.database.migration.modules=AWE,SCHEDULER,NOTIFIER,AWE-REACT

# Database HSQL
spring.datasource.jndi-name=
spring.datasource.platform=hsqldb
spring.datasource.url=jdbc:hsqldb:file:tests/test-angular-redux/target/db/awe-angular-redux
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.hsqldb.jdbc.JDBCDriver

################################################
# Cache configuration
################################################
spring.cache.type=simple
spring.cache.jcache.config=

################################################
# Numeric configuration
################################################
settings.numbers.options.wEmpty=null

################################################
# Swagger configuration
################################################
swagger.enabled=true

################################################
# Session configuration
################################################
#spring.session.store-type=jdbc
#spring.session.jdbc.initialize-schema=always
## Path to the SQL file to use to initialize the database schema.
#spring.session.jdbc.schema=classpath:org/springframework/session/jdbc/schema-hsqldb.sql

# specific properties file: Uncomment to use
# properties.specific=file:${ENVIRONMENT_VARIABLE_OR_PROPERTY}/specific.properties

################################################
# Email
################################################
awe.mail.enabled=true
# Mail authorization
awe.mail.auth=false
# Mail host
awe.mail.host=almeml1.almis.local
# Mail port
awe.mail.port=25
# Mail user
awe.mail.user=
# Mail password
awe.mail.pass=
# Mail debug
awe.mail.debug=true
# Mail SSL
# awe.mail.ssl=true
# Mail TLS
# awe.mail.tls=true
# Mail localhost
# awe.mail.localhost=localhost