--------------------------------------------------------
--  UPDATE HISope columns IN audit tables
--------------------------------------------------------
ALTER TABLE HISope MODIFY HISope CHAR(100);
ALTER TABLE HISAweAppPar MODIFY HISope CHAR(100);
ALTER TABLE HISAweThm MODIFY HISope CHAR(100);
ALTER TABLE HISAwePro MODIFY HISope CHAR(100);
ALTER TABLE HISAweDbs MODIFY HISope CHAR(100);
ALTER TABLE HISAweSit MODIFY HISope CHAR(100);
ALTER TABLE HISAweMod MODIFY HISope CHAR(100);
ALTER TABLE HISAweSitModDbs MODIFY HISope CHAR(100);
ALTER TABLE HISAweModOpe MODIFY HISope CHAR(100);
ALTER TABLE HISAweModPro MODIFY HISope CHAR(100);
ALTER TABLE HISAweEmlSrv MODIFY HISope CHAR(100);
ALTER TABLE HISAweScrCnf MODIFY HISope CHAR(100);
ALTER TABLE HISAweScrRes MODIFY HISope CHAR(100);
ALTER TABLE HISAweQue MODIFY HISope CHAR(100);
