#!/usr/bin/env node
'use strict';

/**
 * Generates the properties page of the site (website/docs/properties.md) from the Spring configuration metadata of the AWE modules.
 *
 * Usage:
 *   node scripts/properties-reference/generate.js [--out <file>] [--snapshot <file>]
 *   node scripts/properties-reference/generate.js --refresh [--root <repo>] [--snapshot <file>]
 *
 * The metadata (META-INF/spring-configuration-metadata.json) is only produced by a Maven build, which the website build does not run,
 * so the generator reads a committed snapshot (data/spring-configuration-metadata.json). "--refresh" rewrites that snapshot from the
 * modules built under --root (run "mvn process-classes" first); a test fails when the snapshot differs from the built metadata.
 *
 * The page is regenerated at every start/build and is git-ignored. To make sure a hand-written page is never overwritten, the output
 * file must be missing or carry the generated marker.
 */

const fs = require('node:fs');
const path = require('node:path');

const {MODULES, metadataFiles, snapshotFromFiles, normalize} = require('./metadata');
const {MARKER, renderPage} = require('./render');
const {propertyReport, formatReport} = require('./report');

const WEBSITE = path.resolve(__dirname, '..', '..');
const REPO = path.resolve(WEBSITE, '..');
const CONTENT_DIR = path.join(__dirname, 'content');
const DEFAULT_SNAPSHOT = path.join(__dirname, 'data', 'spring-configuration-metadata.json');
const DEFAULT_OUT = path.join(WEBSITE, 'docs', 'properties.md');

function parseArgs(argv) {
	const options = {out: DEFAULT_OUT, snapshot: DEFAULT_SNAPSHOT, root: REPO, refresh: false};
	for (let i = 0; i < argv.length; i++) {
		if (argv[i] === '--refresh') {
			options.refresh = true;
			continue;
		}
		const key = {'--out': 'out', '--snapshot': 'snapshot', '--root': 'root'}[argv[i]];
		if (!key || argv[i + 1] === undefined) {
			throw new Error(`Usage: generate.js [--refresh] [--out <file>] [--snapshot <file>] [--root <repo>] (got "${argv.slice(i).join(' ')}")`);
		}
		options[key] = path.resolve(argv[++i]);
	}
	return options;
}

function assertSafeOutput(out) {
	if (fs.existsSync(out) && !fs.readFileSync(out, 'utf8').includes(MARKER)) {
		throw new Error(
			`Refusing to overwrite ${out}: it is not generated by the properties reference (no generated marker). ` +
			'The page is generated now: move any hand-written text to website/scripts/properties-reference/content and delete the file.',
		);
	}
}

function loadContent(contentDir) {
	const read = (file) => fs.readFileSync(path.join(contentDir, file), 'utf8');
	const {groups, hidden} = JSON.parse(read('groups.json'));
	const snippets = {};
	for (const file of fs.readdirSync(contentDir)) {
		if (file.endsWith('.md')) {
			snippets[file] = read(file);
		}
	}
	return {groups, hidden, preface: snippets['preface.md'], appendix: snippets['appendix.md'], snippets};
}

function build({snapshot, contentDir}) {
	if (!fs.existsSync(snapshot)) {
		throw new Error(`Cannot generate the properties reference: ${snapshot} does not exist. Create it with "npm --prefix website run refresh:properties" after "mvn process-classes".`);
	}
	const {groups, hidden, preface, appendix, snippets} = loadContent(contentDir);
	const entries = normalize(JSON.parse(fs.readFileSync(snapshot, 'utf8')), {hidden});
	return {page: renderPage(entries, groups, {preface, appendix, snippets}), entries};
}

function generate({out = DEFAULT_OUT, snapshot = DEFAULT_SNAPSHOT, contentDir = CONTENT_DIR} = {}) {
	assertSafeOutput(out);
	const {page, entries} = build({snapshot, contentDir});
	fs.mkdirSync(path.dirname(out), {recursive: true});
	fs.writeFileSync(out, page);
	return {report: propertyReport(entries), entries};
}

/** Rewrites the snapshot from the metadata that Maven generated in the modules under `root`. */
function refreshSnapshot({root = REPO, snapshot = DEFAULT_SNAPSHOT} = {}) {
	const {files, missing} = metadataFiles(root);
	if (missing.length > 0) {
		throw new Error(
			`Cannot refresh the snapshot: no spring-configuration-metadata.json in ${missing.join(', ')}. ` +
			`Run "mvn process-classes -DskipTests" for the ${MODULES.length} modules first.`,
		);
	}
	const data = snapshotFromFiles(files);
	fs.mkdirSync(path.dirname(snapshot), {recursive: true});
	fs.writeFileSync(snapshot, `${JSON.stringify(data, null, 2)}\n`);
	return {count: data.properties.length};
}

/**
 * Generates the page when it is missing or differs from what would be generated now (stale snapshot or content): used by
 * docusaurus.config.js so any docusaurus command, with or without the npm pre-scripts, finds an up to date page.
 */
// Set by bin/website-maintenance-docs.sh while it swaps a maintenance line's docs in as the current docs to snapshot
// them with docs:version: that line has its own hand-written properties page, which must be left as it is.
const SKIP_ENV = 'AWE_SKIP_PROPERTIES_REFERENCE';

function skipped(env) {
	return env[SKIP_ENV] === '1';
}

function ensureGenerated({out = DEFAULT_OUT, snapshot = DEFAULT_SNAPSHOT, contentDir = CONTENT_DIR, env = process.env} = {}) {
	if (skipped(env)) {
		return;
	}
	assertSafeOutput(out);
	const {page} = build({snapshot, contentDir});
	if (!fs.existsSync(out) || fs.readFileSync(out, 'utf8') !== page) {
		fs.mkdirSync(path.dirname(out), {recursive: true});
		fs.writeFileSync(out, page);
	}
}

if (require.main === module) {
	const options = parseArgs(process.argv.slice(2));
	if (skipped(process.env)) {
		console.log(`Properties reference not generated: ${SKIP_ENV}=1 (a maintenance line is being snapshotted)`);
	} else if (options.refresh) {
		const {count} = refreshSnapshot(options);
		console.log(`Properties snapshot: ${count} properties written to ${path.relative(process.cwd(), options.snapshot)}`);
	} else {
		const {report} = generate(options);
		console.log(`Properties reference written to ${path.relative(process.cwd(), options.out)}`);
		console.log(formatReport(report));
	}
}

module.exports = {generate, refreshSnapshot, ensureGenerated, parseArgs, DEFAULT_SNAPSHOT, DEFAULT_OUT, CONTENT_DIR, SKIP_ENV};
