'use strict';

const {byName} = require('./metadata');

/** Renders the properties page (MDX) from the normalized entries, the group definitions and the hand-written texts. */

const MARKER = '{/* Generated by website/scripts/properties-reference from the Spring configuration metadata. Do not edit: change the hand-written texts in website/scripts/properties-reference/content or the Java javadoc, then regenerate. */}';

/** Splits a text into code spans (kept as they are) and the rest. */
function splitCode(text) {
	return text.split(/(``[^]*?``|`[^`]*`)/g);
}

/** Escapes a table cell for MDX: pipes everywhere, braces and angle brackets outside code spans. */
function escapeCell(text) {
	return splitCode(text)
		.map((part, index) => {
			const escaped = part.replace(/\|/g, '\\|');
			if (index % 2 === 1) {
				return escaped;
			}
			return escaped
				.replace(/\{/g, '\\{')
				.replace(/\}/g, '\\}')
				.replace(/<br\/>/g, '\u0000')
				.replace(/</g, '&lt;')
				.replace(/>/g, '&gt;')
				.replace(/\u0000/g, '<br/>');
		})
		.join('');
}

function codeSpan(value) {
	if (!value) {
		return '';
	}
	const escaped = value.replace(/\|/g, '\\|');
	return value.includes('`') ? `\`\` ${escaped} \`\`` : `\`${escaped}\``;
}

function groupOf(name, groups) {
	let best;
	for (const group of groups) {
		if ((name === group.prefix || name.startsWith(`${group.prefix}.`)) && (!best || group.prefix.length > best.prefix.length)) {
			best = group;
		}
	}
	return best;
}

/** Description cell: a visible marker first when the property is deprecated. */
function describe(entry) {
	if (!entry.deprecated) {
		return escapeCell(entry.description);
	}
	const {replacement, reason} = entry.deprecated;
	const note = [replacement ? `: use ${codeSpan(replacement)} instead.` : '.', reason ? ` ${escapeCell(reason)}` : ''].join('');
	return `**Deprecated**${note} ${escapeCell(entry.description)}`;
}

function renderTable(entries) {
	const lines = [
		'| Name | Type | Description | Default value |',
		'|------|------|-------------|---------------|',
	];
	for (const entry of entries) {
		lines.push(
			`| <Anchor id="${entry.name}"/> [${entry.name}](#${entry.name}) | ${escapeCell(entry.type)} | ${describe(entry)} | ${codeSpan(entry.defaultValue)} |`,
		);
	}
	return lines.join('\n');
}

function snippet(snippets, file) {
	if (!(file in snippets)) {
		throw new Error(`Hand-written content file ${file} not found`);
	}
	return snippets[file].trim();
}

/**
 * @param entries normalized properties
 * @param groups [{id (the heading anchor), title, prefix, intro?, outro?}] in page order; a property goes to the longest matching prefix
 * @param options {preface, appendix, snippets}: hand-written texts (the preface starts with the front matter)
 */
function renderPage(entries, groups, {preface, appendix, snippets = {}}) {
	const buckets = new Map(groups.map((group) => [group, []]));
	const other = [];
	for (const entry of [...entries].sort(byName)) {
		const group = groupOf(entry.name, groups);
		(group ? buckets.get(group) : other).push(entry);
	}

	const parts = [preface.trim(), MARKER];
	for (const [group, groupEntries] of buckets) {
		if (groupEntries.length === 0) {
			continue;
		}
		const intro = group.intro || `These are the configuration properties with the prefix \`${group.prefix}\`.`;
		parts.push(`## ${group.title} {#${group.id}}\n\n${intro}\n\n${renderTable(groupEntries)}`);
		if (group.outro) {
			parts.push(snippet(snippets, group.outro));
		}
	}
	if (other.length > 0) {
		parts.push(`## Other properties {#other-properties}\n\nProperties with a prefix that has no section of its own.\n\n${renderTable(other)}`);
	}
	parts.push(appendix.trim());
	return `${parts.join('\n\n')}\n`;
}

module.exports = {MARKER, renderPage, escapeCell, codeSpan};
