apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: awe-ingress
  labels:
    name: awe-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: staging-static-ip
    networking.gke.io/managed-certificates: aweframework-certs
spec:
  rules:
    - host: staging.aweframework.com
      http:
        paths:
        - backend:
            serviceName: awe-boot-service-staging
            servicePort: 80
    - host: react-staging.aweframework.com
      http:
        paths:
        - backend:
            serviceName: awe-react-service-staging
            servicePort: 80