--------------------------------------------------------
--  DDL for Table AweSchExeLog
--  Bounded task execution log window
--------------------------------------------------------
CREATE TABLE "AWESCHEXELOG"
(
    "IDETSK" NUMBER(*, 0),
    "EXETSK" NUMBER(*, 0),
    "SRC"    VARCHAR2(1 BYTE),
    "SEC"    VARCHAR2(1 BYTE),
    "SLT"    NUMBER(*, 0),
    "LINNUM" NUMBER(*, 0),
    "LINTXT" VARCHAR2(4000 BYTE),
    "LOGDAT" timestamp
);

ALTER TABLE "AWESCHEXELOG"
    MODIFY ("IDETSK" NOT NULL ENABLE);
ALTER TABLE "AWESCHEXELOG"
    MODIFY ("EXETSK" NOT NULL ENABLE);
ALTER TABLE "AWESCHEXELOG"
    MODIFY ("SRC" NOT NULL ENABLE);
ALTER TABLE "AWESCHEXELOG"
    MODIFY ("SEC" NOT NULL ENABLE);
ALTER TABLE "AWESCHEXELOG"
    MODIFY ("SLT" NOT NULL ENABLE);
ALTER TABLE "AWESCHEXELOG"
    MODIFY ("LINNUM" NOT NULL ENABLE);
ALTER TABLE "AWESCHEXELOG"
    MODIFY ("LOGDAT" NOT NULL ENABLE);

CREATE UNIQUE INDEX "PK_AWESCHEXELOG" ON "AWESCHEXELOG" ("IDETSK", "EXETSK", "SRC", "SEC", "SLT");
CREATE INDEX "AWESCHEXELOGI1" ON "AWESCHEXELOG" ("IDETSK", "EXETSK", "LOGDAT");

ALTER TABLE "AWESCHEXELOG"
    ADD PRIMARY KEY ("IDETSK", "EXETSK", "SRC", "SEC", "SLT");
