################################################
# Base config property file
# Configure awe and specific application
################################################
################################################
# Security base properties
################################################
# Jasypt properties (for decrypting properties)
jasypt.encryptor.password=${awe.security.master.key:B1Le3s%25abc75TeBe05}
jasypt.encryptor.algorithm=PBEWithMD5AndDES
jasypt.encryptor.iv-generator-classname=org.jasypt.iv.NoIvGenerator
jasypt.encryptor.keyObtentionIterations=1000
jasypt.encryptor.poolSize=1
jasypt.encryptor.providerName=SunJCE
jasypt.encryptor.saltGeneratorClassname=org.jasypt.salt.RandomSaltGenerator
jasypt.encryptor.stringOutputType=base64

################################################
# Application base properties
################################################
# Spring multipart configuration override
spring.servlet.multipart.max-file-size=${awe.application.component.upload-max-file-size:100MB}
spring.servlet.multipart.max-request-size=${awe.application.component.upload-max-file-size:100MB}
# ThymeLeaf configuration properties
spring.thymeleaf.html.prefix=classpath:/templates/
spring.thymeleaf.html.suffix=.html
spring.thymeleaf.html.cache=false
spring.thymeleaf.css.prefix=classpath:/static/css/
spring.thymeleaf.css.cache=false
# Metrics management
spring.sleuth.async.enabled=false

################################################
# Cache base properties
################################################
# Cache type, auto-detected according to the environment by default.
spring.cache.type=none

################################################
# Database base properties
################################################
spring.flyway.enabled=false
spring.flyway.baselineOnMigrate=true
spring.flyway.locations=classpath:db/migration/{vendor}

###############################################
# Spring session properties
###############################################
# Spring session persistence source
spring.session.store-type=NONE
########### REDIS CONFIGURATION ###############
## Sessions flush mode.
spring.session.redis.flush-mode=on-save
## Namespace for keys used to store sessions.
spring.session.redis.namespace=awe:session