################################################
# Session Config File
# Configurate session parameters
################################################

################################################
# Session configuration
################################################

################################################
# Session parameter list, separated by comma (,)
################################################
session.parameters=module,site,database

################################################
# Session parameter value queries
################################################
session.module.query=ModNamByOpeSel
session.site.query=SitNamByOpeSel
session.database.query=DbsAlsBySitModSel

###############################################
############# SPRING SESSION ##################
###############################################

###############################################
########### SESSION PERSISTENCE ###############
###############################################
# Spring session persistence source
spring.session.store-type=NONE

########### REDIS CONFIGURATION ###############
## Sessions flush mode.
spring.session.redis.flush-mode=on-save
## Namespace for keys used to store sessions.
spring.session.redis.namespace=awe:session

########## HAZELCAST CONFIGURATION ############
# Sessions flush mode.
spring.session.hazelcast.flush-mode=on-save
# Name of the map used to store sessions.
spring.session.hazelcast.map-name=awe:session:sessions
