-- Profiles
Insert into AwePro (IdePro, Acr, Nam, IdeThm, ScrIni, Res, Act) values ('2','GNR','General','1',null,'general','1');
Insert into AwePro (IdePro, Acr, Nam, IdeThm, ScrIni, Res, Act) values ('3','OPE','Operator','1',null,'operator','1');
Insert into AwePro (IdePro, Acr, Nam, IdeThm, ScrIni, Res, Act) values ('4','TST','Test','1',null,'test','1');

-- Update ProKey
UPDATE AweKey SET KeyVal = '5' where KeyNam = 'ProKey';

-- Insert AweMod
Insert into AweMod (IdeMod, Nam, ScrIni, IdeThm, Act, Ord) values (1,	'Test',	'Dbs',	4,	1, 2);
Insert into AweMod (IdeMod, Nam, ScrIni, IdeThm, Act, Ord) values (2,	'Base',	'Sit',	2,	1, 1);

-- Update ModKey
UPDATE AweKey SET KeyVal = '3' where KeyNam = 'ModKey';

-- Insert AweDbs
Insert into AweDbs (IdeDbs, Als, Des, Dct, Dbt, Drv, DbsUsr, DbsPwd, Typ, Dbc, Act) values (1	,'awedb1','AWE DB 1','J','hsql','org.hsqldb.jdbc.JDBCDriver','sa', null,'Des','jdbc:hsqldb:file:awe-tests/awe-boot/target/db/awe-boot',1);
Insert into AweDbs (IdeDbs, Als, Des, Dct, Dbt, Drv, DbsUsr, DbsPwd, Typ, Dbc, Act) values (2	,'awedb2','AWE DB 2','J','hsql','org.hsqldb.jdbc.JDBCDriver','sa', null,'Des','jdbc:hsqldb:file:awe-tests/awe-boot/target/db/awe-boot',1);
Insert into AweDbs (IdeDbs, Als, Des, Dct, Dbt, Drv, DbsUsr, DbsPwd, Typ, Dbc, Act) values (3	,'awedb3','AWE DB 3','J','hsql','org.hsqldb.jdbc.JDBCDriver','sa', null,'Des','jdbc:hsqldb:file:awe-tests/awe-boot/target/db/awe-boot',1);

-- Update DbsKey
UPDATE AweKey
SET KeyVal = '4'
where KeyNam = 'DbsKey';

-- Insert AweModPro
insert into AweModPro (IdeModPro, IdeMod, IdePro, Ord)
values (1, 1, 1, null);
insert into AweModPro (IdeModPro, IdeMod, IdePro, Ord)
values (2, 2, 1, null);
insert into AweModPro (IdeModPro, IdeMod, IdePro, Ord)
values (3, 2, 2, null);
insert into AweModPro (IdeModPro, IdeMod, IdePro, Ord)
values (4, 2, 3, null);

-- Update ModProKey
UPDATE AweKey
SET KeyVal = '5'
where KeyNam = 'ModProKey';

--------------------------------------------------------
--  TESTING TABLES
--------------------------------------------------------

CREATE TABLE IF NOT EXISTS DummyClobTestTable
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY,
    textFile LONGVARCHAR -- CLOB TYPE
);

CREATE TABLE IF NOT EXISTS TST_COUNTRY
(
    ID           INTEGER
        CONSTRAINT PK_COUNTRY PRIMARY KEY NOT NULL,
    COUNTRY_NAME VARCHAR(50),
    COUNTRY_CODE VARCHAR(3)
);
CREATE UNIQUE INDEX IF NOT EXISTS IDX_COUNTRY ON TST_COUNTRY (COUNTRY_NAME);


CREATE TABLE IF NOT EXISTS TST_CUSTOMER
(
    ID               INTEGER
        CONSTRAINT PK_CUSTOMER PRIMARY KEY NOT NULL,
    CUSTOMER_NAME    VARCHAR(255),
    CUSTOMER_ADDRESS VARCHAR(255),
    COUNTRY_ID       INTEGER               NOT NULL,
    CUSTOMER_DATE    DATE                  NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS IDX_CUSTOMER ON TST_CUSTOMER (CUSTOMER_NAME);
ALTER TABLE TST_CUSTOMER
    ADD CONSTRAINT IF NOT EXISTS FK_COUNTRIES FOREIGN KEY (COUNTRY_ID) REFERENCES TST_COUNTRY (ID);

-- Insert Countries
Insert into TST_COUNTRY (ID, COUNTRY_NAME, COUNTRY_CODE)
values ('1', 'Spain', 'ESP');
Insert into TST_COUNTRY (ID, COUNTRY_NAME, COUNTRY_CODE)
values ('2', 'France', 'FRA');
Insert into TST_COUNTRY (ID, COUNTRY_NAME, COUNTRY_CODE)
values ('3', 'United States', 'USA');
Insert into TST_COUNTRY (ID, COUNTRY_NAME, COUNTRY_CODE)
values ('4', 'Portugal', 'POR');
Insert into TST_COUNTRY (ID, COUNTRY_NAME, COUNTRY_CODE)
values ('5', 'Italy', 'ITA');
Insert into TST_COUNTRY (ID, COUNTRY_NAME, COUNTRY_CODE)
values ('6', 'United Kingdom', 'UK');

UPDATE AweKey
SET KeyVal = '7'
where KeyNam = 'CountryKey';

-- Insert Customers
Insert into TST_CUSTOMER (ID, CUSTOMER_NAME, CUSTOMER_ADDRESS, COUNTRY_ID, CUSTOMER_DATE)
values ('1', 'Customer1', 'Liverpool Street 4, London', '6', '2021-02-10 00:00:00');
Insert into TST_CUSTOMER (ID, CUSTOMER_NAME, CUSTOMER_ADDRESS, COUNTRY_ID, CUSTOMER_DATE)
values ('2', 'Customer2', 'Gran Vía 1, Madrid', '1', '2020-08-14 00:00:00');
Insert into TST_CUSTOMER (ID, CUSTOMER_NAME, CUSTOMER_ADDRESS, COUNTRY_ID, CUSTOMER_DATE)
values ('3', 'Customer3', 'Santa Clara 34, Zamora', '1', '2021-06-05 00:00:00');
Insert into TST_CUSTOMER (ID, CUSTOMER_NAME, CUSTOMER_ADDRESS, COUNTRY_ID, CUSTOMER_DATE)
values ('4', 'Customer4', '5th Ave 112, New York', '3', '2021-01-18 00:00:00');
Insert into TST_CUSTOMER (ID, CUSTOMER_NAME, CUSTOMER_ADDRESS, COUNTRY_ID, CUSTOMER_DATE)
values ('5', 'Customer5', 'Via del Corso 29, Rome', '5', '2020-06-28 00:00:00');

UPDATE AweKey
SET KeyVal = '6'
where KeyNam = 'CustomerKey';

-- Insert other user
Insert into ope (IdeOpe, l1_nom, l1_pas, l1_con, l1_dev, l1_act, l1_trt, l1_uti, l1_opr, l1_dat, imp_nom, dat_mod, l1_psd, l1_lan, l1_sgn, PcPrn, EmlSrv, EmlAdr, OpeNam, IdePro, IdeThm)
values (2,'pei','5e52fee47e6b070565f74372468cdc699de89107',0,null,1,null,0,null,null,'none',null,null,'ENG',1,null,null,'pei@test.com','Manager',1,1);
UPDATE AweKey SET KeyVal = '3' where KeyNam = 'OpeKey';