-- ------------------------------------------------------
--  UPDATE HISope columns IN audit tables
-- ------------------------------------------------------
ALTER TABLE HISAweSchCal ALTER COLUMN HISope TYPE CHAR(100), ALTER COLUMN HISope DROP NOT NULL;
ALTER TABLE HISAweSchCalDat ALTER COLUMN HISope TYPE CHAR(100), ALTER COLUMN HISope DROP NOT NULL;
ALTER TABLE HISAweSchSrv ALTER COLUMN HISope TYPE CHAR(100), ALTER COLUMN HISope DROP NOT NULL;
ALTER TABLE HISAweSchTsk ALTER COLUMN HISope TYPE CHAR(100), ALTER COLUMN HISope DROP NOT NULL;
ALTER TABLE HISAweSchTskLch ALTER COLUMN HISope TYPE CHAR(100), ALTER COLUMN HISope DROP NOT NULL;
ALTER TABLE HISAweSchTskPar ALTER COLUMN HISope TYPE CHAR(100), ALTER COLUMN HISope DROP NOT NULL;