apiVersion: v1
kind: Service
metadata:
  name: awe-boot-service
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: awe-boot
    env: staging