gitops:
  manifest_projects:
    - id: "aweframework/awe-gke-config"
      paths:
        - glob: 'staging/awe-boot/awe*.{yaml,yml,json}'
        - glob: 'production/awe-boot/awe*.{yaml,yml,json}'
        - glob: 'staging/awe-react/awe*.{yaml,yml,json}'
        - glob: 'production/awe-react/awe*.{yaml,yml,json}'
        - glob: 'staging/redis/*.{yaml,yml,json}'
        - glob: 'production/redis/*.{yaml,yml,json}'