apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:4.1.2-management
          ports:
            - containerPort: 5672
              name: amqp
            - containerPort: 15672
              name: management
            - containerPort: 61613
              name: stomp
          volumeMounts:
            - name: rabbitmq-config
              mountPath: /etc/rabbitmq
          readinessProbe:
            tcpSocket:
              port: 61613
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 30
            periodSeconds: 30
      volumes:
        - name: rabbitmq-config
          configMap:
            name: rabbitmq-config