-- ------------------------------------------------------
--  UPDATE HISope columns IN audit tables
-- ------------------------------------------------------

DROP INDEX IF EXISTS HISAweSchCalI1 on HISAweSchCal;
DROP INDEX IF EXISTS HISAweSchCalDatI1 on HISAweSchCalDat;
DROP INDEX IF EXISTS HISAweSchSrvI1 on HISAweSchSrv;
DROP INDEX IF EXISTS HISAweSchTskI1 on HISAweSchTsk;
DROP INDEX IF EXISTS HISAweSchTskLchI1 on HISAweSchTskLch;
DROP INDEX IF EXISTS HISAweSchTskParI1 on HISAweSchTskPar;

ALTER TABLE HISAweSchCal ALTER COLUMN HISope CHAR(100) NULL;
ALTER TABLE HISAweSchCalDat ALTER COLUMN HISope CHAR(100) NULL;
ALTER TABLE HISAweSchSrv ALTER COLUMN HISope CHAR(100) NULL;
ALTER TABLE HISAweSchTsk ALTER COLUMN HISope CHAR(100) NULL;
ALTER TABLE HISAweSchTskLch ALTER COLUMN HISope CHAR(100) NULL;
ALTER TABLE HISAweSchTskPar ALTER COLUMN HISope CHAR(100) NULL;

CREATE INDEX HISAweSchCalI1 ON HISAweSchCal (HISope, HISdat, HISact);
CREATE INDEX HISAweSchCalDatI1 ON HISAweSchCalDat (HISope, HISdat, HISact);
CREATE INDEX HISAweSchSrvI1 ON HISAweSchSrv (HISope, HISdat, HISact);
CREATE INDEX HISAweSchTskI1 ON HISAweSchTsk (HISope, HISdat, HISact);
CREATE INDEX HISAweSchTskLchI1 ON HISAweSchTskLch (HISope, HISdat, HISact);
CREATE INDEX HISAweSchTskParI1 ON HISAweSchTskPar (HISope, HISdat, HISact);