apiVersion: apps/v1
kind: Deployment
metadata:
  name: awe-react
  namespace: staging
  annotations:
    app.gitlab.com/env: staging
    app.gitlab.com/app: aweframework-awe-react
  labels:
    app: awe-react
    env: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: awe-react
      env: staging
  template:
    metadata:
      annotations:
        app.gitlab.com/env: staging
        app.gitlab.com/app: aweframework-awe-react
        version: 1.0.0-SNAPSHOT
      labels:
        app: awe-react
        env: staging
    spec:
      containers:
        - name: awe-react
          image: registry.gitlab.com/aweframework/awe-react/awe-react:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /mnt/secrets
              name: secrets
              readOnly: true
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: cloud
            - name: MYSQL_URL
              valueFrom:
                secretKeyRef:
                  key: mysql-url
                  name: awe-react
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  key: mysql-username
                  name: awe-react
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mysql-password
                  name: awe-react
            - name: MYSQL_CLIENT_KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: client-keystore-password
                  name: awe-react
            - name: TRUSTSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: truststore-password
                  name: awe-react
          resources:
            limits:
              memory: 2Gi
            requests:
              memory: 256Mi
      volumes:
        - name: secrets
          secret:
            secretName: awe-react
            items:
              - key: truststore.jks
                path: truststore.jks
              - key: mysql-client-keystore.p12
                path: mysql-client-keystore.p12
      imagePullSecrets:
        - name: registry.gitlab.com