apiVersion: apps/v1
kind: Deployment
metadata:
  name: awe-boot
  labels:
    app: awe-boot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: awe-boot
  template:
    metadata:
      labels:
        app: awe-boot
    spec:
      containers:
      - name: awe-boot
        image: awe-boot
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
          - mountPath: /mnt/secrets
            name: secrets
            readOnly: true
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: cloud
          - name: MYSQL_URL
            valueFrom:
              secretKeyRef:
                key: mysql-url
                name: awe-boot
          - name: MYSQL_USERNAME
            valueFrom:
              secretKeyRef:
                key: mysql-username
                name: awe-boot
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: mysql-password
                name: awe-boot
          - name: MYSQL_CLIENT_KEYSTORE_PASSWORD
            valueFrom:
              secretKeyRef:
                key: client-keystore-password
                name: awe-boot
          - name: TRUSTSTORE_PASSWORD
            valueFrom:
              secretKeyRef:
                key: truststore-password
                name: awe-boot
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 256Mi
      volumes:
        - name: secrets
          secret:
            secretName: awe-boot
            items:
              - key: truststore.jks
                path: truststore.jks
              - key: mysql-client-keystore.p12
                path: mysql-client-keystore.p12