-- ------------------------------------------------------
--  UPDATE HISope columns IN audit tables
-- ------------------------------------------------------
ALTER TABLE HISope MODIFY HISope CHAR(100) NULL;
ALTER TABLE HISAweAppPar MODIFY HISope CHAR(100) NULL;
ALTER TABLE HISAweThm MODIFY HISope CHAR(100) NULL;
ALTER TABLE HISAwePro MODIFY HISope CHAR(100) NULL;
ALTER TABLE HISAweDbs MODIFY HISope CHAR(100) NULL;
ALTER TABLE HISAweSit MODIFY HISope CHAR(100) NULL;
ALTER TABLE HISAweMod MODIFY HISope CHAR(100) NULL;
ALTER TABLE HISAweSitModDbs MODIFY HISope CHAR(100) NULL;
ALTER TABLE HISAweModOpe MODIFY HISope CHAR(100) NULL;
ALTER TABLE HISAweModPro MODIFY HISope CHAR(100) NULL;
ALTER TABLE HISAweEmlSrv MODIFY HISope CHAR(100) NULL;
ALTER TABLE HISAweScrCnf MODIFY HISope CHAR(100) NULL;
ALTER TABLE HISAweScrRes MODIFY HISope CHAR(100) NULL;
ALTER TABLE HISAweQue MODIFY HISope CHAR(100) NULL;
